# Generated by Django 5.1.7 on 2025-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="current_draft_round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="draft_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="draft_order",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="draft_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="max_rounds",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="event",
            name="max_team_size",
            field=models.IntegerField(default=11),
        ),
    ]
