# Generated by Django 4.1.5 on 2023-01-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='nothing',
            new_name='location',
        ),
    ]
