# Generated by Django 5.1.7 on 2025-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_event_current_draft_round_event_draft_in_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player_registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
