# Generated by Django 5.1.7 on 2025-05-21 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_event_player_registration_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
