# Generated by Django 4.1.5 on 2023-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_is_admin_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
