# Generated by Django 5.1.7 on 2025-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_event_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="remember_me_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="remember_me_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
