# Generated by Django 4.1.5 on 2023-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_draft_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='draft_date',
            field=models.DateField(null=True),
        ),
    ]
