# Generated by Django 5.1.7 on 2025-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_user_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cricket_participant",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="noreply@sportspot.com", max_length=254, unique=True
            ),
        ),
    ]
