# Generated by Django 3.2 on 2023-01-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_draft_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='draft_date',
            field=models.DateTimeField(null=True),
        ),
    ]
