# Generated by Django 4.1.5 on 2023-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_id_alter_submission_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prizes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
