# Generated by Django 4.1.5 on 2023-01-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_event_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nothing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
