# Generated by Django 4.1.5 on 2023-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_nothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cricket_praticipant',
            field=models.BooleanField(default='True', null=True),
        ),
    ]
