# Generated by Django 4.1.5 on 2023-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_cricket_praticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cricket_praticipant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
